apiVersion: v1
kind: Pod
metadata:
  name: helloworldnodejs.example.com
  labels:
    app: helloworldnodejs
spec:
  containers:
    - name: k8s-demo
      image: xuyongzhidocker/demo-app:node-demo-0.0.2
      ports:
      - name: nodejs-port
        containerPort: 3001
  imagePullSecrets:
    - name: myregistrysecret
